### ISSUE TITLE
Через гитхаб удобнее

### ISSUE THREAD

**Issue by futoke** [become-iron/Vasya_Web_EDA#1]
А так я не сразу смог скачать ваш проект, антивирус аутлука (niuitmo сделано на платформе Office 365) сильно ругался, что ваш код -- вирус.

**Comment by become-iron** [comment]
Предлагаю тогда вам здесь вносить предложения: каждое предложение -- в отдельное issue

**Comment by futoke** [comment]
Ок

**Comment by become-iron** [comment]
Также вам, наверное, лучше отслеживать репозиторий, чтобы оперативно следить за изменениями
![default](https://user-images.githubusercontent.com/8668962/30341193-735ede7e-97f5-11e7-9b15-b15750b1b6c3.png)
